### ISSUE TITLE
FreeBSD Foundation vs. Project

### ISSUE THREAD

**Issue by GeorgLink** [Cultivate-Community-Team-2/focus-communities#4]
In your discussion about FreeBSD, it is not clear whether you are describing the foundation alone or also the project. For the FreeBSD community, the foundation is a part of it but the Project is where the community gets together.

Maybe update the description to highlight the structure and workings of the FreeBSD project.

**Comment by stevenhe-river** [comment]
Thanks Georg...added this context and description on the project vs the foundation
