### ISSUE TITLE
Describe relationship between Node.js and OpenJS Froundation

### ISSUE THREAD

**Issue by GeorgLink** [Cultivate-Community-Team-2/focus-communities#5]
Node.js seems to be only one of many projects under the OpenJS Foundation. In describing the Node.js community, we may want to make sure to not confuse the foundation's work that spans other communities but recognize its influence.

**Comment by stevenhe-river** [comment]
Entered a short comment about the relationship between the 2 and entered a link to the announcement of the merger between Node.js Foundation and JS Foundation
