### ISSUE TITLE
Artifacts

### ISSUE THREAD

**Issue by GeorgLink** [Cultivate-Community-Team-2/focus-communities#6]
Your artifacts are focused on documentation which is definitely something the community creates together.

I would recommend adding other things the community creates together:
* Mailing list archives
* Source code
* Websites

**Comment by brlcad** [comment]
The table at the top covered all the technical resources including websites, code, mailing lists, and CI/testing systems, while the textual information below aimed to focus exclusively on artifacts specifically pertaining to governance.  I'll update the page to hopefully make this more clear.

**Comment by brlcad** [comment]
Thanks for the feedback.  Our page has been updated in 3ba11bf to more clearly show that technical community artifacts are included in the top table while governance is in the sections below.
